### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by EpikNohVuh** [EpikNohVuh/GroupRepository#3]
## User Story
As a user, I would like to know where all the local dog parks are in the nearby area.

## Acceptance Criteria
- [x] Sign up for Google Maps API
- [x] Figure out how target Dog Parks within Google Maps for a specific local.
- [x] How to implement the Google Map. (size displayed)
*https://developers.google.com/maps/documentation/javascript/tutorial

- [x] Going through the process of hiding the API per Google requirements

**Comment by AndreaLabis** [comment]
All done with map and hiding the API key
